INSERT INTO songs_title (number, title) VALUES (1,	'Békességre vágyik minden ember');
INSERT INTO songs_title (number, title) VALUES (2,	'Ahogy a felhők fölött…');
INSERT INTO songs_title (number, title) VALUES (3,	'Jézus, jöjj közénk');
INSERT INTO songs_title (number, title) VALUES (4,	'Amikor úgy érzed');
INSERT INTO songs_title (number, title) VALUES (5,	'E földön sok baj vesz körül');
INSERT INTO songs_title (number, title) VALUES (6,	'A mélyből hozzád száll szavam');
INSERT INTO songs_title (number, title) VALUES (7,	'Egyszer szembenéztem');
INSERT INTO songs_title (number, title) VALUES (8,	'Ó, haldd meg imám');
INSERT INTO songs_title (number, title) VALUES (9,	'Jöjj, te szegény');
INSERT INTO songs_title (number, title) VALUES (10,	'Taníts, Uram meghajlani');
INSERT INTO songs_title (number, title) VALUES (11,	'Kedves barátom');
INSERT INTO songs_title (number, title) VALUES (12,	'Kegyelemből léphetünk be');
INSERT INTO songs_title (number, title) VALUES (13,	'Teremts bennem');
INSERT INTO songs_title (number, title) VALUES (14,	'Magányos voltam');
INSERT INTO songs_title (number, title) VALUES (15,	'Úgy érzem, néha');
INSERT INTO songs_title (number, title) VALUES (16,	'Nincs helyed Jézus számára');
INSERT INTO songs_title (number, title) VALUES (17,	'Adj új erőt Urunk');
INSERT INTO songs_title (number, title) VALUES (18,	'Sokszor úgy érzem');
INSERT INTO songs_title (number, title) VALUES (19,	'Esdve kérlek, jó Atyám');
INSERT INTO songs_title (number, title) VALUES (20,	'Boldog ember az…');
INSERT INTO songs_title (number, title) VALUES (21,	'Ezt a világot');
INSERT INTO songs_title (number, title) VALUES (22,	'Nem szeret senki');
INSERT INTO songs_title (number, title) VALUES (23,	'Remélj, remélj');
INSERT INTO songs_title (number, title) VALUES (24,	'Van úgy, hogy fáradt és nehéz');
INSERT INTO songs_title (number, title) VALUES (25,	'Formáld át szívem');
INSERT INTO songs_title (number, title) VALUES (26,	'Vándorutam');
INSERT INTO songs_title (number, title) VALUES (27,	'Gyorsan fut az idő');
INSERT INTO songs_title (number, title) VALUES (28,	'Üdvözítőm szeret engem');
INSERT INTO songs_title (number, title) VALUES (29,	'Széjjeljártam a világban');
INSERT INTO songs_title (number, title) VALUES (30,	'Légy csendben');
INSERT INTO songs_title (number, title) VALUES (31,	'Mért félig');
INSERT INTO songs_title (number, title) VALUES (32,	'Ha az Úr szomorít');
INSERT INTO songs_title (number, title) VALUES (33,	'Mossál meg engem');
INSERT INTO songs_title (number, title) VALUES (34,	'Isten nem ígért');
INSERT INTO songs_title (number, title) VALUES (35,	'Mint szarvas');
INSERT INTO songs_title (number, title) VALUES (36,	'Hozzád jövünk, Uram');
INSERT INTO songs_title (number, title) VALUES (37,	'Időnk fut egyre');
INSERT INTO songs_title (number, title) VALUES (38,	'Hívlak, Uram, szükségem van');
INSERT INTO songs_title (number, title) VALUES (39,	'Uram, itt vagyok');
INSERT INTO songs_title (number, title) VALUES (40,	'A Bárány vére');
INSERT INTO songs_title (number, title) VALUES (41,	'A sír üres');
INSERT INTO songs_title (number, title) VALUES (42,	'Az Úr jósága, hogy még élünk');
INSERT INTO songs_title (number, title) VALUES (43,	'Aki hozzám fordul');
INSERT INTO songs_title (number, title) VALUES (44,	'Azért jött Jézus');
INSERT INTO songs_title (number, title) VALUES (45,	'Amikor teljes sötétség');
INSERT INTO songs_title (number, title) VALUES (46,	'Ama szép hon felé');
INSERT INTO songs_title (number, title) VALUES (47,	'Atyám, két kezedben');
INSERT INTO songs_title (number, title) VALUES (48,	'Csend van bennem');
INSERT INTO songs_title (number, title) VALUES (49,	'Egyetlen forrása minden kegynek');
INSERT INTO songs_title (number, title) VALUES (50,	'Emlékezzél meg');
INSERT INTO songs_title (number, title) VALUES (51,	'Életutam, míg a földön járom');
INSERT INTO songs_title (number, title) VALUES (52,	'Ne félj, mert enyém vagy');
INSERT INTO songs_title (number, title) VALUES (53,	'Elmondanám milyen nagyon');
INSERT INTO songs_title (number, title) VALUES (54,	'Ragyogsz-e még');
INSERT INTO songs_title (number, title) VALUES (55,	'Fáradtan, bűnbe veszve');
INSERT INTO songs_title (number, title) VALUES (56,	'Óh, forrongó gazdag árja');
INSERT INTO songs_title (number, title) VALUES (57,	'Jézus szíve megbocsát');
INSERT INTO songs_title (number, title) VALUES (58,	'Hisszük, meghallgat az Úr');
INSERT INTO songs_title (number, title) VALUES (59,	'Két irdatlan fa összeróva');
INSERT INTO songs_title (number, title) VALUES (60,	'Így szól ma tehozzád Jézus');
INSERT INTO songs_title (number, title) VALUES (61,	'Az Úr van itt');
INSERT INTO songs_title (number, title) VALUES (62,	'Bízom Benned, Uram Jézus');
INSERT INTO songs_title (number, title) VALUES (63,	'Krisztus hívása hangzik');
INSERT INTO songs_title (number, title) VALUES (64,	'Én nem tudok nélküled élni');
INSERT INTO songs_title (number, title) VALUES (65,	'Van még számomra is bocsánat');
INSERT INTO songs_title (number, title) VALUES (66,	'Jézus, véred megtisztít');
INSERT INTO songs_title (number, title) VALUES (67,	'Úgy szerette Isten');
INSERT INTO songs_title (number, title) VALUES (68,	'Hatalmas vagy');
INSERT INTO songs_title (number, title) VALUES (69,	'Nem hallod-e');
INSERT INTO songs_title (number, title) VALUES (70,	'Életem csak kegyelem');
INSERT INTO songs_title (number, title) VALUES (71,	'Mikor vízen mégy át');
INSERT INTO songs_title (number, title) VALUES (72,	'Elszállnak már az évek');
INSERT INTO songs_title (number, title) VALUES (73,	'Vándor vagyok');
INSERT INTO songs_title (number, title) VALUES (74,	'Még nem is éltem én');
INSERT INTO songs_title (number, title) VALUES (75,	'Minden nap veled leszek');
INSERT INTO songs_title (number, title) VALUES (76,	'Milyen jó, milyen jó');
INSERT INTO songs_title (number, title) VALUES (77,	'Földön és égen');
INSERT INTO songs_title (number, title) VALUES (78,	'Soha nem volt még');
INSERT INTO songs_title (number, title) VALUES (79,	'Van egy jó hely');
INSERT INTO songs_title (number, title) VALUES (80,	'Örvendjetek, mert Isten úgy szeret');
INSERT INTO songs_title (number, title) VALUES (81,	'Hogyha Jézus');
INSERT INTO songs_title (number, title) VALUES (82,	'Nincs határa Jézus szerelmének');
INSERT INTO songs_title (number, title) VALUES (83,	'Isten hív, te el ne küldd');
INSERT INTO songs_title (number, title) VALUES (84,	'Tündöklő Atyánk kegyelme');
INSERT INTO songs_title (number, title) VALUES (85,	'Vágyol-e elhagyni');
INSERT INTO songs_title (number, title) VALUES (86,	'Ó, mily hű barátunk Jézus');
INSERT INTO songs_title (number, title) VALUES (87,	'Jöjj el az élet vizéhez');
INSERT INTO songs_title (number, title) VALUES (88,	'Mily drága nekünk ez a jó hír');
INSERT INTO songs_title (number, title) VALUES (89,	'Légy Te az első');
INSERT INTO songs_title (number, title) VALUES (90,	'Jézus, Messiás');
INSERT INTO songs_title (number, title) VALUES (91,	'Magára vette szennyes ruhámat');
INSERT INTO songs_title (number, title) VALUES (92,	'Ó, érthetetlen kegyelem');
INSERT INTO songs_title (number, title) VALUES (93,	'Jöjj, az Úr vár reád');
INSERT INTO songs_title (number, title) VALUES (94,	'Megváltva');
INSERT INTO songs_title (number, title) VALUES (95,	'Amikor megérint');
INSERT INTO songs_title (number, title) VALUES (96,	'Vonj magadhoz, ó, Uram');
INSERT INTO songs_title (number, title) VALUES (97,	'Minden nap');
INSERT INTO songs_title (number, title) VALUES (98,	'Megváltóm, oly boldoggá tettél');
INSERT INTO songs_title (number, title) VALUES (99,	'Lényed érint');
INSERT INTO songs_title (number, title) VALUES (100,	'Jöjj, ha éhes vagy');
INSERT INTO songs_title (number, title) VALUES (101,	'Jöjj, Szentlélek');
INSERT INTO songs_title (number, title) VALUES (102,	'Jézus, ünnepeljük győzelmed');
INSERT INTO songs_title (number, title) VALUES (103,	'Jöjj el ma tűzzel');
INSERT INTO songs_title (number, title) VALUES (104,	'A Mester itt van');
INSERT INTO songs_title (number, title) VALUES (105,	'Jézus, ó Jézus');
INSERT INTO songs_title (number, title) VALUES (106,	'Egykor oly kedves dolgok');
INSERT INTO songs_title (number, title) VALUES (107,	'Feladtad méltó, nagy Neved');
INSERT INTO songs_title (number, title) VALUES (108,	'Egyedül csak Te vagy');
INSERT INTO songs_title (number, title) VALUES (109,	'Áradj folyó');
INSERT INTO songs_title (number, title) VALUES (110,	'Az életem ajtaján ott van már');
INSERT INTO songs_title (number, title) VALUES (111,	'Ragadj magaddal');
INSERT INTO songs_title (number, title) VALUES (112,	'Te vagy váltságom');
INSERT INTO songs_title (number, title) VALUES (113,	'A nap keltétől');
INSERT INTO songs_title (number, title) VALUES (114,	'Atyját és az anyját');
INSERT INTO songs_title (number, title) VALUES (115,	'A tegnap terhe');
INSERT INTO songs_title (number, title) VALUES (116,	'De sokszor nem értem');
INSERT INTO songs_title (number, title) VALUES (117,	'Áldott légy, jó Atyám');
INSERT INTO songs_title (number, title) VALUES (118,	'Édesatyám');
INSERT INTO songs_title (number, title) VALUES (119,	'Kegyelem, nagy kegyelem');
INSERT INTO songs_title (number, title) VALUES (120,	'El Saddaj');
INSERT INTO songs_title (number, title) VALUES (121,	'Elmúlik ez a világ');
INSERT INTO songs_title (number, title) VALUES (122,	'A napfelkeltétől');
INSERT INTO songs_title (number, title) VALUES (123,	'Emberek vagy angyalok nyelvén');
INSERT INTO songs_title (number, title) VALUES (124,	'Kész az én szívem, Uram');
INSERT INTO songs_title (number, title) VALUES (125,	'Ez a szó, szeretet');
INSERT INTO songs_title (number, title) VALUES (126,	'Kész van az én szívem');
INSERT INTO songs_title (number, title) VALUES (127,	'Hívlak, Uram');
INSERT INTO songs_title (number, title) VALUES (128,	'Minden mi él');
INSERT INTO songs_title (number, title) VALUES (129,	'Hozzád száll az énekünk');
INSERT INTO songs_title (number, title) VALUES (130,	'Hála, hogy itt a csendes reggel');
INSERT INTO songs_title (number, title) VALUES (131,	'Messze fenn egy hegyen');
INSERT INTO songs_title (number, title) VALUES (132,	'Tehozzád kiáltok');
INSERT INTO songs_title (number, title) VALUES (133,	'Miénk a hit');
INSERT INTO songs_title (number, title) VALUES (134,	'Újszövetséged elfogadom');
INSERT INTO songs_title (number, title) VALUES (135,	'Nagy Istenem');
INSERT INTO songs_title (number, title) VALUES (136,	'Ő az Úr');
INSERT INTO songs_title (number, title) VALUES (137,	'Nézd meg az évszakokat');
INSERT INTO songs_title (number, title) VALUES (138,	'Szeretet áradjon köztünk');
INSERT INTO songs_title (number, title) VALUES (139,	'Oh, hála az Úrnak');
INSERT INTO songs_title (number, title) VALUES (140,	'Jézus Krisztusom');
INSERT INTO songs_title (number, title) VALUES (141,	'Oly jó tudni azt');
INSERT INTO songs_title (number, title) VALUES (142,	'Jézus, neved oly csodálatos');
INSERT INTO songs_title (number, title) VALUES (143,	'Sűrű sötét van');
INSERT INTO songs_title (number, title) VALUES (144,	'Járom a zarándok utjait');
INSERT INTO songs_title (number, title) VALUES (145,	'Szent színed elé járulunk');
INSERT INTO songs_title (number, title) VALUES (146,	'Tavasz suhan');
INSERT INTO songs_title (number, title) VALUES (147,	'Ha visszanézek');
INSERT INTO songs_title (number, title) VALUES (148,	'Úr Jézus, Megváltóm');
INSERT INTO songs_title (number, title) VALUES (149,	'Jövel Jézus, légy itt vélünk');
INSERT INTO songs_title (number, title) VALUES (150,	'Uram Tehozzád futok');
INSERT INTO songs_title (number, title) VALUES (151,	'Hálát adok, Uram');
INSERT INTO songs_title (number, title) VALUES (152,	'Áldd lelkem Istened');
INSERT INTO songs_title (number, title) VALUES (153,	'Tegyél engem pecsétté');
INSERT INTO songs_title (number, title) VALUES (154,	'Áldott légy, Istenem');
INSERT INTO songs_title (number, title) VALUES (155,	'Rád bízom');
INSERT INTO songs_title (number, title) VALUES (156,	'Erőt adsz minden helyzetben');
INSERT INTO songs_title (number, title) VALUES (157,	'Istenem, nem értem');
INSERT INTO songs_title (number, title) VALUES (158,	'Hűséged végtelen');
INSERT INTO songs_title (number, title) VALUES (159,	'Jöjj mihozzánk, Jézus');
INSERT INTO songs_title (number, title) VALUES (160,	'Jézus, hű Megváltó');
INSERT INTO songs_title (number, title) VALUES (161,	'Nincs szebb név');
INSERT INTO songs_title (number, title) VALUES (162,	'Jézussal járok minden nap');
INSERT INTO songs_title (number, title) VALUES (163,	'Örülj, örvendj, énekeljél');
INSERT INTO songs_title (number, title) VALUES (164,	'Mindeddig megőrzött az Úr');
INSERT INTO songs_title (number, title) VALUES (165,	'Róla beszél fű, virág');
INSERT INTO songs_title (number, title) VALUES (166,	'Most ujjongjon a szívünk');
INSERT INTO songs_title (number, title) VALUES (167,	'Székely asztali áldás');
INSERT INTO songs_title (number, title) VALUES (168,	'Nagy Király');
INSERT INTO songs_title (number, title) VALUES (169,	'Imádlak én Istenem');
INSERT INTO songs_title (number, title) VALUES (170,	'Jézus a jó Pásztor');
INSERT INTO songs_title (number, title) VALUES (171,	'Jézus Krisztus Úr');
INSERT INTO songs_title (number, title) VALUES (172,	'Védelmezz Istenem');
INSERT INTO songs_title (number, title) VALUES (173,	'Még többet Tőled');
INSERT INTO songs_title (number, title) VALUES (174,	'Élet van tebenned');
INSERT INTO songs_title (number, title) VALUES (175,	'Dicsérd, dicsérd');
INSERT INTO songs_title (number, title) VALUES (176,	'Jöjj, itt az idő');
INSERT INTO songs_title (number, title) VALUES (177,	'Legyen a mi hangunk');
INSERT INTO songs_title (number, title) VALUES (178,	'Szóljon az ének');
INSERT INTO songs_title (number, title) VALUES (179,	'Minden lélegzetemmel');
INSERT INTO songs_title (number, title) VALUES (180,	'Fejet hajt a mindenség');
INSERT INTO songs_title (number, title) VALUES (181,	'Isten jó');
INSERT INTO songs_title (number, title) VALUES (182,	'Gyere te is, áldjuk együtt');
INSERT INTO songs_title (number, title) VALUES (183,	'Csak vidáman');
INSERT INTO songs_title (number, title) VALUES (184,	'Elindulunk égő szívvel');
INSERT INTO songs_title (number, title) VALUES (185,	'Szerettem volna nagyra törni');
INSERT INTO songs_title (number, title) VALUES (186,	'A legnagyobb cél e földön');
INSERT INTO songs_title (number, title) VALUES (187,	'Tégy engem békeköveteddé');
INSERT INTO songs_title (number, title) VALUES (188,	'A Te nevedben');
INSERT INTO songs_title (number, title) VALUES (189,	'Válasszatok');
INSERT INTO songs_title (number, title) VALUES (190,	'Eldőlt a szívemben');
INSERT INTO songs_title (number, title) VALUES (191,	'Dávid egykor');
INSERT INTO songs_title (number, title) VALUES (192,	'Kegyelmed Úr Jézus');
INSERT INTO songs_title (number, title) VALUES (193,	'Igéddel áldj meg');
INSERT INTO songs_title (number, title) VALUES (194,	'Egymásnak terhét');
INSERT INTO songs_title (number, title) VALUES (195,	'Együtt a sereg');
INSERT INTO songs_title (number, title) VALUES (196,	'Ha utam borítja');
INSERT INTO songs_title (number, title) VALUES (197,	'Úr Jézus, taníts meg örülni');
INSERT INTO songs_title (number, title) VALUES (198,	'Ha Mesternek hívtok');
INSERT INTO songs_title (number, title) VALUES (199,	'Elhívtalak');
INSERT INTO songs_title (number, title) VALUES (200,	'Keressétek az én orcámat');
INSERT INTO songs_title (number, title) VALUES (201,	'Futunk, s nem lankadunk');
INSERT INTO songs_title (number, title) VALUES (202,	'Légy jó vitéze Krisztusnak');
INSERT INTO songs_title (number, title) VALUES (203,	'Indulj az úton');
INSERT INTO songs_title (number, title) VALUES (204,	'Krisztus Testének tagja vagy már');
INSERT INTO songs_title (number, title) VALUES (205,	'Minden szerinted, legyen');
INSERT INTO songs_title (number, title) VALUES (206,	'Tudom, az Úrnak terve van velem');
INSERT INTO songs_title (number, title) VALUES (207,	'Tégy egyé, Urunk');
INSERT INTO songs_title (number, title) VALUES (208,	'Szolgálni néked');
INSERT INTO songs_title (number, title) VALUES (209,	'Itt a földön nincs');
INSERT INTO songs_title (number, title) VALUES (210,	'Ó, Jézus, amikor sokan');
INSERT INTO songs_title (number, title) VALUES (211,	'Légy Jézus Krisztus harcosa');
INSERT INTO songs_title (number, title) VALUES (212,	'Találkozni jöttem Veled');
INSERT INTO songs_title (number, title) VALUES (213,	'Isten minden gyermekének');
INSERT INTO songs_title (number, title) VALUES (214,	'Szeretnék lenni én');
INSERT INTO songs_title (number, title) VALUES (215,	'Legyen áldás az úton');
INSERT INTO songs_title (number, title) VALUES (216,	'Lehet mindig hitben élni');
INSERT INTO songs_title (number, title) VALUES (217,	'Megkötöm szívemet');
INSERT INTO songs_title (number, title) VALUES (218,	'Eljöttem, Istenem');
INSERT INTO songs_title (number, title) VALUES (219,	'Kenyered és borod táplál');
INSERT INTO songs_title (number, title) VALUES (220,	'Csak Istenben');
INSERT INTO songs_title (number, title) VALUES (221,	'51. Zsoltár');
INSERT INTO songs_title (number, title) VALUES (222,	'Esti imádság');
INSERT INTO songs_title (number, title) VALUES (223,	'Hallod-e fiú');
INSERT INTO songs_title (number, title) VALUES (224,	'Vallomás');
INSERT INTO songs_title (number, title) VALUES (225,	'Lelkem áldjad');
INSERT INTO songs_title (number, title) VALUES (226,	'Úgy szerette');
INSERT INTO songs_title (number, title) VALUES (227,	'Sokszor…');
INSERT INTO songs_title (number, title) VALUES (228,	'Nincs aki…');
INSERT INTO songs_title (number, title) VALUES (229,	'Szeretnélek meglátni');
INSERT INTO songs_title (number, title) VALUES (230,	'Méltó vagy');
INSERT INTO songs_title (number, title) VALUES (231,	'Napkeleten');
INSERT INTO songs_title (number, title) VALUES (232,	'Vezess');
INSERT INTO songs_title (number, title) VALUES (233,	'Örüljetek');
INSERT INTO songs_title (number, title) VALUES (234,	'Ima');
INSERT INTO songs_title (number, title) VALUES (235,	'Jézus az életem Megváltója');
INSERT INTO songs_title (number, title) VALUES (236,	'Ha vándorutam csüggedten járom');
INSERT INTO songs_title (number, title) VALUES (237,	'Itt az este');
INSERT INTO songs_title (number, title) VALUES (238,	'Áld meg édes Istenünk');
INSERT INTO songs_title (number, title) VALUES (239,	'Áldott a férfi');
INSERT INTO songs_title (number, title) VALUES (240,	'Az Úr gondol ránk');
INSERT INTO songs_title (number, title) VALUES (241,	'Uatam a fény');
INSERT INTO songs_title (number, title) VALUES (242,	'Több erőt');
INSERT INTO songs_title (number, title) VALUES (243,	'Jöjj ma atyádhoz');
INSERT INTO songs_title (number, title) VALUES (244,	'Tied a dicsõség');
INSERT INTO songs_title (number, title) VALUES (245,	'Múlnak az évek');
INSERT INTO songs_title (number, title) VALUES (246,	'Ó, Uram, szívem');
INSERT INTO songs_title (number, title) VALUES (247,	'Te éltetsz engem');
INSERT INTO songs_title (number, title) VALUES (248,	'Rejts most el');
INSERT INTO songs_title (number, title) VALUES (249,	'Csak Benned');
INSERT INTO songs_title (number, title) VALUES (250,	'Semmim sem volt nekem');
INSERT INTO songs_title (number, title) VALUES (251,	'Mikor még semmi nem létezett');
INSERT INTO songs_title (number, title) VALUES (252,	'Oly bús az életem');
INSERT INTO songs_title (number, title) VALUES (253,	'Hús-vér templom');
INSERT INTO songs_title (number, title) VALUES (254,	'Ma csak álmodom arról');
INSERT INTO songs_title (number, title) VALUES (255,	'Röpke fohászként');
INSERT INTO songs_title (number, title) VALUES (256,	'Krisztusban van reménységem');
INSERT INTO songs_title (number, title) VALUES (257,	'Tüzed, Uram, Jézus');
INSERT INTO songs_title (number, title) VALUES (258,	'Egyetlen vagy');
INSERT INTO songs_title (number, title) VALUES (259,	'Ó, mély atyai szeretet');
INSERT INTO songs_title (number, title) VALUES (260,	'Minden kár és szemét');
INSERT INTO songs_title (number, title) VALUES (261,	'Tékozló');
INSERT INTO songs_title (number, title) VALUES (262,	'Zengd velünk');
INSERT INTO songs_title (number, title) VALUES (263,	'Őrzöm kincseim');
INSERT INTO songs_title (number, title) VALUES (264,	'Akkor majd táncolva');
INSERT INTO songs_title (number, title) VALUES (265,	'Ez az a dal');
INSERT INTO songs_title (number, title) VALUES (266,	'Homokba írva');
INSERT INTO songs_title (number, title) VALUES (267,	'Ízleld és lásd');
INSERT INTO songs_title (number, title) VALUES (268,	'Én még mit sem tudtam rólad');
INSERT INTO songs_title (number, title) VALUES (269,	'Szentlélek, jöjj');
INSERT INTO songs_title (number, title) VALUES (270,	'Csipkebokor');
INSERT INTO songs_title (number, title) VALUES (271,	'Boldog mosoly az arcomon');
INSERT INTO songs_title (number, title) VALUES (272,	'Jézus, én Téged választottalak');
INSERT INTO songs_title (number, title) VALUES (273,	'Ahol az élet vize árad');
INSERT INTO songs_title (number, title) VALUES (274,	'Ha mástól már segítség nem jő');
INSERT INTO songs_title (number, title) VALUES (275,	'Áldom szent neved');
INSERT INTO songs_title (number, title) VALUES (276,	'Mindnyájan vétkeztek');
INSERT INTO songs_title (number, title) VALUES (277,	'Jegyezd meg jól');
INSERT INTO songs_title (number, title) VALUES (278,	'Így szól az Úr hozzád');
INSERT INTO songs_title (number, title) VALUES (279,	'Zene nem szól már');
INSERT INTO songs_title (number, title) VALUES (280,	'Kérünk, sziklánk Te légy a hitben');
INSERT INTO songs_title (number, title) VALUES (281,	'A nagy mélységből szüntelen');
INSERT INTO songs_title (number, title) VALUES (282,	'Valami eltörött idebent, nézd');
INSERT INTO songs_title (number, title) VALUES (283,	'Sok mindent megpróbáltam');
INSERT INTO songs_title (number, title) VALUES (284,	'Ha reánk tör a homály');
INSERT INTO songs_title (number, title) VALUES (285,	'A hegyek s tengerek felett');
INSERT INTO songs_title (number, title) VALUES (286,	'Jézus Úr a mennyben s mindenek felett');
INSERT INTO songs_title (number, title) VALUES (287,	'Nincs olyan fájdalom, gond');
INSERT INTO songs_title (number, title) VALUES (288,	'Néha úgy érzem');
INSERT INTO songs_title (number, title) VALUES (289,	'Jobb az engedelmesség');
INSERT INTO songs_title (number, title) VALUES (290,	'Mint szarvas hűs folyóvízhez (Pintér)');
INSERT INTO songs_title (number, title) VALUES (291,	'Ki olyan, mint Ő');
INSERT INTO songs_title (number, title) VALUES (292,	'Békesség Királya');
INSERT INTO songs_title (number, title) VALUES (293,	'Imádkozz minden reggel');
INSERT INTO songs_title (number, title) VALUES (294,	'Mint szarvas hűs vízforrásra (Mért csüggedsz)');
INSERT INTO songs_title (number, title) VALUES (295,	'Eljött hozzám');
INSERT INTO songs_title (number, title) VALUES (296,	'Feltört talaj');
INSERT INTO songs_title (number, title) VALUES (297,	'Áldjátok az Urat');
INSERT INTO songs_title (number, title) VALUES (298,	'Kicsiny kis fényemmel');
INSERT INTO songs_title (number, title) VALUES (299,	'A nap bíborban áll');
INSERT INTO songs_title (number, title) VALUES (300,	'Légy Krisztusnak jó katonája');
INSERT INTO songs_title (number, title) VALUES (301,	'Mily gyönyörűség');
INSERT INTO songs_title (number, title) VALUES (302,	'Szánjátok oda a testetek');
INSERT INTO songs_title (number, title) VALUES (303,	'A szeretet nem fogy el');